# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0002_cpumemory_finalresult_log_multitest_pppoesessiontest_testcasestate_usertranstest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasestate',
            name='add_time',
            field=models.CharField(default='-1', help_text='添加时间', max_length=100),
        ),
    ]
