# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0003_auto_20170531_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcasestate',
            name='add_time',
        ),
        migrations.AddField(
            model_name='testcasestate',
            name='type_name',
            field=models.CharField(default='-1', help_text='测试用例类型', max_length=100),
        ),
    ]
