# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0004_auto_20170531_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasestate',
            name='add_time',
            field=models.CharField(default='-1', help_text='添加时间', max_length=100),
        ),
    ]
