# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 02:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0005_testcasestate_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multitest',
            name='ipoe_avg_latency',
        ),
        migrations.RemoveField(
            model_name='multitest',
            name='ipoe_max_latency',
        ),
        migrations.RemoveField(
            model_name='multitest',
            name='ipoe_min_latency',
        ),
        migrations.RemoveField(
            model_name='multitest',
            name='iptv_avg_latency',
        ),
        migrations.RemoveField(
            model_name='multitest',
            name='iptv_max_latency',
        ),
        migrations.RemoveField(
            model_name='multitest',
            name='iptv_min_latency',
        ),
        migrations.RemoveField(
            model_name='multitest',
            name='pppoe_avg_latency',
        ),
        migrations.RemoveField(
            model_name='multitest',
            name='pppoe_max_latency',
        ),
        migrations.RemoveField(
            model_name='multitest',
            name='pppoe_min_latency',
        ),
        migrations.RemoveField(
            model_name='multitest',
            name='voice_avg_latency',
        ),
        migrations.RemoveField(
            model_name='multitest',
            name='voice_max_latency',
        ),
        migrations.RemoveField(
            model_name='multitest',
            name='voice_min_latency',
        ),
        migrations.AddField(
            model_name='multitest',
            name='avg_latency',
            field=models.FloatField(default='-1', help_text='平均时延'),
        ),
        migrations.AddField(
            model_name='multitest',
            name='connect_rate',
            field=models.FloatField(default='-1', help_text='上线速率'),
        ),
        migrations.AddField(
            model_name='multitest',
            name='frame_size',
            field=models.IntegerField(default='-1', help_text='帧大小'),
        ),
        migrations.AddField(
            model_name='multitest',
            name='max_latency',
            field=models.FloatField(default='-1', help_text='最大时延'),
        ),
        migrations.AddField(
            model_name='multitest',
            name='min_latency',
            field=models.FloatField(default='-1', help_text='最小时延'),
        ),
        migrations.AddField(
            model_name='multitest',
            name='rx_rate',
            field=models.FloatField(default='-1', help_text='接收速率'),
        ),
        migrations.AddField(
            model_name='multitest',
            name='session_num',
            field=models.IntegerField(default='-1', help_text='Session连接数'),
        ),
        migrations.AddField(
            model_name='multitest',
            name='tx_rate',
            field=models.FloatField(default='-1', help_text='发送速率'),
        ),
        migrations.AddField(
            model_name='pppoesessiontest',
            name='connect_rate',
            field=models.FloatField(default='-1', help_text='上线速率'),
        ),
        migrations.AddField(
            model_name='usertranstest',
            name='rx_rate',
            field=models.FloatField(default='-1', help_text='接收速率'),
        ),
        migrations.AlterField(
            model_name='testcasestate',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 1, 10, 44, 28, 625763), help_text='添加时间'),
        ),
    ]
