# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 04:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0007_auto_20170602_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multitest',
            name='avg_latency',
            field=models.CharField(default='-1', help_text='平均时延', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='multitest',
            name='connect_rate',
            field=models.CharField(default='-1', help_text='上线速率', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='multitest',
            name='max_latency',
            field=models.CharField(default='-1', help_text='最大时延', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='multitest',
            name='min_latency',
            field=models.CharField(default='-1', help_text='最小时延', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='multitest',
            name='rx_rate',
            field=models.CharField(default='-1', help_text='接收速率', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='multitest',
            name='tx_rate',
            field=models.CharField(default='-1', help_text='发送速率', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testcasestate',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 2, 12, 57, 28, 43835), help_text='添加时间'),
        ),
    ]
