# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 05:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0010_auto_20170613_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpumemory',
            name='add_time',
            field=models.CharField(default='-1', help_text='添加时间', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cpumemory',
            name='cpu',
            field=models.FloatField(default='-1', help_text='CPU利用率', null=True),
        ),
        migrations.AlterField(
            model_name='cpumemory',
            name='memory',
            field=models.FloatField(default='-1', help_text='Memory利用率', null=True),
        ),
        migrations.AlterField(
            model_name='testcasestate',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 13, 13, 19, 33, 851119), help_text='添加时间'),
        ),
    ]
