# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 03:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0011_auto_20170613_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpumemory',
            name='add_time',
            field=models.IntegerField(default='-1', help_text='添加时间', null=True),
        ),
        migrations.AlterField(
            model_name='testcasestate',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 14, 11, 50, 24, 818253), help_text='添加时间'),
        ),
    ]
