# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 03:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0012_auto_20170614_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasestate',
            name='add_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='添加时间'),
        ),
    ]
