# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0013_auto_20170629_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasestate',
            name='set_timer',
            field=models.IntegerField(default=-1, help_text='测试次数'),
        ),
        migrations.AddField(
            model_name='testcasestate',
            name='set_vender',
            field=models.CharField(default='-1', help_text='厂商名', max_length=100),
        ),
        migrations.AddField(
            model_name='testcasestate',
            name='set_version',
            field=models.CharField(default='-1', help_text='版本号', max_length=100),
        ),
        migrations.AddField(
            model_name='testcasestate',
            name='set_vnf_tpye',
            field=models.CharField(default='-1', help_text='网元类型', max_length=100),
        ),
    ]
