# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0014_auto_20170713_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcasestate',
            old_name='set_vnf_tpye',
            new_name='set_vnf_type',
        ),
    ]
