# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0015_auto_20170719_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasestate',
            name='session_rate',
            field=models.CharField(default='-1', help_text='新建会话速率', max_length=100),
        ),
    ]
