# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0016_testcasestate_session_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcasestate',
            old_name='session_rate',
            new_name='set_session_rate',
        ),
    ]
