# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0018_auto_20170803_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasestate',
            name='set_platform',
            field=models.CharField(default='-1', help_text='云平台名称', max_length=100),
        ),
        migrations.AddField(
            model_name='testcasestate',
            name='set_platform_v',
            field=models.CharField(default='-1', help_text='云平台版本', max_length=100),
        ),
    ]
